spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=wishlist-db;encrypt=true;trustServerCertificate=true;integratedSecurity=true
    username:
    password:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
        show_sql: true